apiVersion: v1
kind: Namespace
metadata:
  name: istio-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: istio-operator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: istio-operator
  name: istio-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: istio-operator
  template:
    metadata:
      labels:
        name: istio-operator
    spec:
      serviceAccountName: istio-operator
      containers:
      - name: istio-operator
        image: istio/operator:1.19.0
        command:
        - operator
        - server
        env:
        - name: WATCH_NAMESPACE
          value: istio-system
        - name: LEADER_ELECTION_NAMESPACE
          value: istio-operator
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-operator
  namespace: istio-operator
